FROM mcr.microsoft.com/dotnet/sdk:10.0@sha256:ed034a8bf0b24ded0cbbac07e17825d8e9ebfe21e308191d0f7421eaf5ad4664 AS build
WORKDIR /src

COPY backend/src/Emi.Qms.Api/Emi.Qms.Api.csproj backend/src/Emi.Qms.Api/
RUN dotnet restore backend/src/Emi.Qms.Api/Emi.Qms.Api.csproj

COPY backend/src/Emi.Qms.Api backend/src/Emi.Qms.Api
RUN dotnet publish backend/src/Emi.Qms.Api/Emi.Qms.Api.csproj \
    --configuration Release \
    --no-restore \
    --output /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0-azurelinux3.0-distroless-extra@sha256:1e70cdf79d1ab86b19e10956407d1f57eb8d9052089c14f2e878f70622713834 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
USER app
ENTRYPOINT ["dotnet", "Emi.Qms.Api.dll"]
