alter table notifications
    drop constraint if exists ck_notifications_source_kind;

alter table notifications
    add constraint ck_notifications_source_kind
    check (source_kind in (
        'Automatic', 'Manual', 'ChannelNotice', 'WorkAssignment', 'PendingAssignment',
        'DailyDigest', 'Escalation', 'System'
    ));

create table sales_billing_request_batches (
    id uuid primary key,
    request_number bigint generated by default as identity unique,
    period_start date not null,
    period_end date not null,
    note text null,
    project_count integer not null,
    workbook_file_name text not null,
    workbook_content_type text not null default 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    workbook_size integer not null,
    workbook_sha256 text not null,
    workbook_content bytea not null,
    created_by_user_id uuid not null references qms_users(id),
    created_at_utc timestamptz not null default now(),
    constraint ck_sales_billing_request_period check (period_start <= period_end),
    constraint ck_sales_billing_request_period_length check (period_end - period_start between 0 and 30),
    constraint ck_sales_billing_request_note check (note is null or char_length(btrim(note)) between 1 and 500),
    constraint ck_sales_billing_request_project_count check (project_count between 1 and 500),
    constraint ck_sales_billing_request_file_name check (workbook_file_name ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$'),
    constraint ck_sales_billing_request_content_type check (workbook_content_type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'),
    constraint ck_sales_billing_request_workbook_size check (workbook_size = octet_length(workbook_content) and workbook_size between 1 and 10485760),
    constraint ck_sales_billing_request_sha check (workbook_sha256 ~ '^[0-9a-f]{64}$')
);

create index ix_sales_billing_request_batches_created
    on sales_billing_request_batches(created_at_utc desc);

create table sales_billing_request_items (
    batch_id uuid not null references sales_billing_request_batches(id) on delete restrict,
    project_id uuid not null references projects(id) on delete restrict,
    row_number integer not null,
    project_code text not null,
    project_title text not null,
    customer_name text not null,
    item_name text not null,
    delivery_location text null,
    first_departure_date date not null,
    last_departure_date date not null,
    active_panel_count integer not null,
    departed_panel_count integer not null,
    sales_amount numeric(18,2) not null,
    currency_code text not null,
    sales_owner_name text not null,
    created_at_utc timestamptz not null default now(),
    primary key (batch_id, project_id),
    constraint ux_sales_billing_request_items_project unique (project_id),
    constraint ux_sales_billing_request_items_row unique (batch_id, row_number),
    constraint ck_sales_billing_request_item_row check (row_number between 1 and 500),
    constraint ck_sales_billing_request_departure_dates check (first_departure_date <= last_departure_date),
    constraint ck_sales_billing_request_panel_counts check (active_panel_count > 0 and departed_panel_count = active_panel_count),
    constraint ck_sales_billing_request_amount check (sales_amount >= 0),
    constraint ck_sales_billing_request_currency check (currency_code ~ '^[A-Z]{3}$')
);

create index ix_sales_billing_request_items_batch
    on sales_billing_request_items(batch_id, row_number);

create table sales_billing_request_operations (
    operation_id uuid primary key,
    batch_id uuid not null references sales_billing_request_batches(id) on delete restrict,
    actor_user_id uuid not null references qms_users(id),
    payload_fingerprint text not null,
    result_projection jsonb not null,
    created_at_utc timestamptz not null default now(),
    constraint ck_sales_billing_request_operation_fingerprint check (payload_fingerprint ~ '^[0-9a-f]{64}$'),
    constraint ck_sales_billing_request_operation_projection check (octet_length(result_projection::text) <= 4096)
);

create table sales_billing_request_download_events (
    id uuid primary key,
    batch_id uuid not null references sales_billing_request_batches(id) on delete restrict,
    downloaded_by_user_id uuid not null references qms_users(id),
    downloaded_at_utc timestamptz not null default now()
);

create index ix_sales_billing_request_download_events_batch
    on sales_billing_request_download_events(batch_id, downloaded_at_utc desc);

create or replace function guard_sales_billing_request_append_only()
returns trigger language plpgsql as $$
begin
    if current_setting('emi_qms.project_purge', true) = 'on' and tg_op = 'DELETE' then
        return old;
    end if;
    raise exception 'Sales billing request records are append-only.';
end $$;

create trigger trg_guard_sales_billing_request_batch
before update or delete on sales_billing_request_batches
for each row execute function guard_sales_billing_request_append_only();

create trigger trg_guard_sales_billing_request_item
before update or delete on sales_billing_request_items
for each row execute function guard_sales_billing_request_append_only();

create trigger trg_guard_sales_billing_request_operation
before update or delete on sales_billing_request_operations
for each row execute function guard_sales_billing_request_append_only();

create trigger trg_guard_sales_billing_request_download
before update or delete on sales_billing_request_download_events
for each row execute function guard_sales_billing_request_append_only();
