-- Dedicated Cheongju module. Tables may exist in each business database; API access is Cheongju-only.
insert into roles(id,code,name) values('20000000-0000-0000-0000-000000000090','interior-busbar-manager','인테리어 부스바 담당자') on conflict(code) do nothing;
create table busbar_settings(singleton boolean primary key default true check(singleton), common_project_code text not null default '');
insert into busbar_settings values(true,'');
create table busbar_product_families(id uuid primary key,code text unique not null,name text not null,is_active boolean not null default true);
create table busbar_materials(id uuid primary key,code text unique not null,name text not null,unit text not null,supply_type text not null check(supply_type in ('사급','도급')),is_active boolean not null default true);
create table busbar_workers(id uuid primary key,code text unique not null,name text not null,is_active boolean not null default true);
create table busbar_boms(id uuid primary key,product_family_id uuid not null references busbar_product_families,version integer not null,created_at_utc timestamptz not null default now(),unique(product_family_id,version));
create table busbar_bom_lines(bom_id uuid references busbar_boms,material_id uuid references busbar_materials,quantity numeric(18,4) not null check(quantity>0),primary key(bom_id,material_id));
create table busbar_projects(id uuid primary key,name text not null,customer_job_number text not null,common_project_code text not null,product_family_id uuid not null references busbar_product_families,requested_quantity integer not null check(requested_quantity>0),destination text not null,due_date date not null);
create table busbar_plans(id uuid primary key,product_family_id uuid not null references busbar_product_families,plan_date date not null,quantity integer not null check(quantity>=0),unique(product_family_id,plan_date));
create table busbar_purchases(id uuid primary key,order_number text not null,material_id uuid not null references busbar_materials,quantity numeric(18,4) not null check(quantity>0),order_date date not null,common_project_code text not null,external_id text unique null,external_status text null,conflict_note text null);
create table busbar_products(id uuid primary key,request_id uuid not null unique,product_family_id uuid not null references busbar_product_families,worker_id uuid not null references busbar_workers,worker_name text not null,number text unique null,manufactured_at_utc timestamptz null,status text not null default 'Draft' check(status in ('Draft','Complete','Cancelled')),bom_id uuid references busbar_boms,public_token text unique not null,revision integer not null default 0,publication_state text not null default 'Pending' check(publication_state in ('Pending','Published','Failed')),published_revision integer not null default 0,publication_error text null,created_by uuid not null references qms_users,photo_registered_by uuid null references qms_users,created_at_utc timestamptz not null default now());
create sequence busbar_product_number_seq;
create table busbar_photos(product_id uuid references busbar_products,side text check(side in ('front','back')),content bytea not null,content_type text not null,registered_at_utc timestamptz not null,registered_by uuid not null references qms_users,primary key(product_id,side));
create table busbar_stock(stock_kind text check(stock_kind in ('Material','Finished')),item_id uuid,balance numeric(18,4) not null default 0,primary key(stock_kind,item_id),check(stock_kind='Material' or (balance>=0 and balance=trunc(balance))));
create table busbar_operations(id uuid primary key,request_id uuid not null unique,request_fingerprint text not null default '',kind text not null,reference_id uuid null,reverses_id uuid unique references busbar_operations,reason text not null,created_by uuid not null references qms_users,created_at_utc timestamptz not null default now());
create table busbar_ledger(id uuid primary key,operation_id uuid not null references busbar_operations,stock_kind text not null,item_id uuid not null,quantity numeric(18,4) not null,foreign key(stock_kind,item_id) references busbar_stock);
create table busbar_shipments(id uuid primary key references busbar_operations,project_id uuid not null references busbar_projects,quantity integer not null check(quantity>0));
create table busbar_receipts(id uuid primary key references busbar_operations,purchase_id uuid not null references busbar_purchases,quantity numeric(18,4) not null check(quantity>0));
create table busbar_audit(id uuid primary key,entity_kind text not null,entity_id uuid not null,reason text not null,changed_by uuid not null references qms_users,changed_at_utc timestamptz not null default now(),before_value jsonb not null,after_value jsonb not null);
create index ix_busbar_ledger_item on busbar_ledger(stock_kind,item_id);
create index ix_busbar_products_publication on busbar_products(publication_state) where status<>'Draft';

-- Photo corrections retain the original normalized image and registration provenance.
create table busbar_photo_history(id uuid primary key,product_id uuid not null references busbar_products,side text not null check(side in ('front','back')),content bytea not null,registered_at_utc timestamptz not null,registered_by uuid not null references qms_users,reason text not null);
