import { beforeEach,expect,it,vi } from 'vitest';
import { render,screen,fireEvent,waitFor } from '@testing-library/react';
import { OsanPersonalHome } from '../src/OsanPersonalHomePage';
import { fetchJson,getOsanProject,listNotices } from '../src/api';
import { recentOsanProjects,rememberOsanProject, type PersonalHomeData } from '../src/osanPersonalHome';
vi.mock('../src/api',()=>({fetchJson:vi.fn(),getOsanProject:vi.fn(),listNotices:vi.fn(),ApiError:class extends Error{status=0}}));
vi.mock('../src/OsanQrScanner',()=>({OsanQrScanner:()=> <div>QR 카메라</div>}));
const props={scope:'actor-a',name:'사용자',department:'품질팀',canCreate:false,onProject:vi.fn(),onStage:vi.fn(),onProgress:vi.fn(),onNotice:vi.fn(),onNotifications:vi.fn(),onCreate:vi.fn(),onScan:vi.fn()};
const fixture:PersonalHomeData={taskTotalCount:1,deadlineTotalCount:0,customers:[],summary:{totalCount:0,inProgressCount:0,holdCount:0,overdueCount:0,openIssueCount:0},tasks:[{id:'r',kind:'rejection',projectId:'p',targetId:'t',stageSequence:3,projectTitle:'제어반',productName:'Rack',stageName:'배선검사',comment:'단자 확인',actorName:'검사자',occurredAtUtc:'2026-09-25T00:00:00Z'}],deadlines:[],news:[]};
beforeEach(()=>{vi.resetAllMocks();localStorage.clear();vi.mocked(fetchJson).mockResolvedValue(fixture);vi.mocked(listNotices).mockResolvedValue({items:[],totalCount:0,page:1,pageSize:5});});
it('고객사 미배정도 직접 받은 반려는 표시하고 전체 고객사로 대체하지 않는다',async()=>{render(<OsanPersonalHome {...props}/>);fireEvent.click(await screen.findByRole('button',{name:/반려 제어반/}));expect(props.onStage).toHaveBeenCalledWith('p','t',3);expect(screen.getByText(/배정된 고객사가 없습니다. 관리자/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'관리 대상 프로젝트 0'})).toBeDisabled();expect(screen.queryByRole('button',{name:'프로젝트 등록'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('tab',{name:'받은 요청 0'}));expect(screen.getByText('확인할 업무가 없습니다.')).toBeInTheDocument();});
it('고객사 및 KPI 이동에 본인 담당 고객사만 전달한다',async()=>{vi.mocked(fetchJson).mockResolvedValue({...fixture,customers:[{notStartedCount:1,completedCount:0,customerId:'c',customerName:'고객A',totalCount:2,inProgressCount:1,holdCount:0,overdueCount:1,openIssueCount:1,progressPercent:50}],summary:{...fixture.summary,totalCount:2,openIssueCount:1}});render(<OsanPersonalHome {...props}/>);fireEvent.click(await screen.findByRole('button',{name:'공정 이상 1'}));expect(props.onProgress).toHaveBeenCalledWith({customers:['고객A'],kpi:'OpenIssue'});const customerRow=screen.getByRole('button',{name:/고객A/});for(const text of ['전체 2건','공정 시작 전 1','공정 진행 중 1','포장완료 0','HOLD 0','전체 공정 진행률50%'])expect(customerRow).toHaveTextContent(text);});
it('공지 읽음은 제목 굵기와 행 전체 링크로 처리하고 알림 기능과 분리한다',async()=>{vi.mocked(listNotices).mockResolvedValue({items:[{noticeId:'n',title:'중요 업데이트',preview:'',isRead:false,pinned:true,authorDisplayName:'관리자',authorDepartmentName:null,createdAtUtc:'2026-09-25T00:00:00Z',canDelete:false,updatedAtUtc:null}],totalCount:1,page:1,pageSize:5});render(<OsanPersonalHome {...props}/>);const row=await screen.findByRole('button',{name:/중요 업데이트/});expect(row).toHaveClass('unread');fireEvent.click(row);expect(props.onNotice).toHaveBeenCalledWith('n');});
it('계정별 방문은 분리되고 현재 프로젝트 권한을 다시 조회한다',async()=>{const id='00000000-0000-0000-0000-000000000001';rememberOsanProject('actor-a',id);expect(recentOsanProjects('actor-b')).toEqual([]);vi.mocked(getOsanProject).mockResolvedValue({projectId:id,title:'최근 프로젝트',productName:'Box',customerName:'고객A',workOrderNumber:'WO-1'} as never);render(<OsanPersonalHome {...props}/>);expect(await screen.findByRole('button',{name:/최근 프로젝트 Box/})).toBeInTheDocument();expect(getOsanProject).toHaveBeenCalledWith(undefined,id,expect.objectContaining({signal:expect.any(AbortSignal)}));});
it('계정 전환 때 이전 응답을 표시하지 않는다',async()=>{let resolveOld!:(v:PersonalHomeData)=>void;vi.mocked(fetchJson).mockImplementationOnce(()=>new Promise(r=>{resolveOld=r;})).mockResolvedValue({...fixture,tasks:[]});const {rerender}=render(<OsanPersonalHome {...props}/>);rerender(<OsanPersonalHome {...props} scope="actor-b"/>);await screen.findByText('확인할 업무가 없습니다.');resolveOld(fixture);await waitFor(()=>expect(screen.queryByRole('button',{name:/반려 제어반/})).not.toBeInTheDocument());});
it('날짜 선택은 일부 홈 일정 대신 담당 고객사와 납기일로 다시 조회하고 다시 누르면 해제한다',async()=>{
 const customer={notStartedCount:1,completedCount:0,customerId:'c',customerName:'고객A',totalCount:2,inProgressCount:1,holdCount:0,overdueCount:0,openIssueCount:0,progressPercent:50};
 vi.mocked(fetchJson).mockImplementation(async(path)=>path.startsWith('/api/osan/dashboard?')?{items:[{projectId:'day-project',title:'선택일 프로젝트',customerName:'고객A',deliveryDate:'2026-09-25',status:'InProgress'}],totalCount:1}:({...fixture,customers:[customer],deadlines:[]}));
 render(<OsanPersonalHome {...props}/>);
 await screen.findByRole('button',{name:'관리 대상 프로젝트 0'});
 const dateButton=screen.getAllByRole('button',{name:/^\d{4}-\d{2}-\d{2} 납기 일정$/})[2];
 const date=dateButton.getAttribute('aria-label')!.slice(0,10);
 fireEvent.click(dateButton);
 expect(await screen.findByRole('button',{name:/선택일 프로젝트/})).toBeInTheDocument();
 const request=vi.mocked(fetchJson).mock.calls.find(([path])=>path.startsWith('/api/osan/dashboard?'))![0];
 const params=new URL(request,'http://localhost').searchParams;
 expect(params.get('dueFrom')).toBe(date);expect(params.get('dueTo')).toBe(date);expect(params.getAll('customer')).toEqual(['고객A']);expect(params.getAll('status')).toEqual(['NotStarted','InProgress']);
 expect(dateButton).toHaveAttribute('aria-pressed','true');fireEvent.click(dateButton);
 expect(screen.queryByRole('button',{name:/선택일 프로젝트/})).not.toBeInTheDocument();expect(dateButton).toHaveAttribute('aria-pressed','false');
});
