import { useEffect, useState, type ReactNode } from 'react';
import { ApiError, getOsanProject, listNotices } from './api';
import { getOsanPersonalHome, recentOsanProjects, type PersonalHomeData, type HomeTask } from './osanPersonalHome';
import type { NoticeListResponse } from './notices';
import type { OsanProjectDetail } from './projects';
import { formatOsanDday, useKoreaDate } from './osanDday';
import { NavigationIcon } from './NavigationIcon';
import { OsanQrScanner } from './OsanQrScanner';
import type { OsanListFilters } from './osanListState';
import { getOsanDashboard } from './osanDashboard';
import './osan-personal-home.css';
type Props={userKey?:string;scope:string;name:string;department:string;canCreate:boolean;onProject:(id:string)=>void;onStage:(projectId:string,targetId:string,stage:number)=>void;onProgress:(filters?:Partial<OsanListFilters>)=>void;onNotice:(id?:string)=>void;onNotifications:()=>void;onCreate:()=>void;onScan:(projectId:string,targetId:string)=>void};
const dateTime=(date:string)=>new Date(date).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
const dateOnly=(date:string)=>new Date(date).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit'});
function Widget({name,title,more,children}:{name:string;title:string;more?:()=>void;children:ReactNode}){return <section className={`widget ${name}`}><div className="widget-title"><h2>{title}</h2>{more&&<button className="text-button" onClick={more}>전체보기 ›</button>}</div>{children}</section>}
export function OsanPersonalHome(props:Props){return <Home key={`${props.scope}:${props.userKey??''}`} {...props}/>}
function Home(p:Props){
 const today=useKoreaDate();const [data,setData]=useState<PersonalHomeData>();const [error,setError]=useState('');const [notices,setNotices]=useState<NoticeListResponse>();const [noticeError,setNoticeError]=useState('');const [recent,setRecent]=useState<{project:OsanProjectDetail;visitedAt:string}[]>();const [recentError,setRecentError]=useState(false);const [refresh,setRefresh]=useState(0);const [tab,setTab]=useState<'all'|'request'|'rejection'>('all');const [expanded,setExpanded]=useState<Record<string,boolean>>({});const [scanning,setScanning]=useState(false);
 useEffect(()=>{const c=new AbortController();let active=true;getOsanPersonalHome(p.userKey,c.signal).then(v=>{if(active){setData(v);setError('');}}).catch(e=>{if(active)setError(e instanceof ApiError&&e.status===403?'홈을 볼 권한이 없습니다.':e instanceof Error?e.message:'홈을 불러오지 못했습니다.');});return()=>{active=false;c.abort();};},[p.userKey,refresh]);
 useEffect(()=>{let active=true;listNotices(p.userKey,1,5).then(v=>{if(active){setNotices(v);setNoticeError('');}}).catch(()=>{if(active)setNoticeError('공지를 불러오지 못했습니다.');});return()=>{active=false;};},[p.userKey,refresh]);
 useEffect(()=>{const c=new AbortController();let active=true;Promise.allSettled(recentOsanProjects(p.scope).map(async v=>({project:await getOsanProject(p.userKey,v.projectId,{signal:c.signal}),visitedAt:v.visitedAt}))).then(results=>{if(active){setRecent(results.flatMap(r=>r.status==='fulfilled'?[r.value]:[]));setRecentError(results.some(r=>r.status==='rejected'&&!(r.reason instanceof ApiError&&[403,404,410].includes(r.reason.status))));}});return()=>{active=false;c.abort();};},[p.scope,p.userKey,refresh]);
 useEffect(()=>{const update=()=>setRefresh(v=>v+1);const timer=window.setInterval(update,60000);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update);};},[]);
 const [selectedDate,setSelectedDate]=useState<string|null>(null);
 const [dayResult,setDayResult]=useState<{key:string;items:PersonalHomeData['deadlines'];total:number;error?:string}>();
 const customerKey=JSON.stringify(data?.customers.map(c=>c.customerName)??[]);
 const dayKey=`${selectedDate}:${customerKey}`;
 useEffect(()=>{
   if(!selectedDate)return;
   const customers=JSON.parse(customerKey) as string[];
   if(!customers.length)return;
   const controller=new AbortController();let active=true;
   getOsanDashboard(p.userKey,{customers,search:'',statuses:['NotStarted','InProgress'],dueFrom:selectedDate,dueTo:selectedDate,kpi:null,page:1,view:'progress'},controller.signal)
     .then(result=>{if(active)setDayResult({key:dayKey,items:result.items,total:result.totalCount});})
     .catch(()=>{if(active)setDayResult({key:dayKey,items:[],total:0,error:'선택한 날짜의 납기 일정을 불러오지 못했습니다.'});});
   return()=>{active=false;controller.abort();};
 },[selectedDate,customerKey,dayKey,p.userKey,refresh]);
 const allCustomers=data?.customers.map(c=>c.customerName)??[];
 const dayLoading=!!selectedDate&&!!allCustomers.length&&dayResult?.key!==dayKey;
 const dayError=selectedDate&&dayResult?.key===dayKey?dayResult.error:undefined;
 const deadlines=selectedDate?(dayResult?.key===dayKey?dayResult.items:[]):data?.deadlines;
 const deadlineTotal=selectedDate?(dayResult?.key===dayKey?dayResult.total:0):data?.deadlineTotalCount;
 const deadlineFilter={statuses:['NotStarted','InProgress'],dueFrom:selectedDate??'',dueTo:selectedDate??new Date(Date.parse(`${today}T00:00:00Z`)+14*86400000).toISOString().slice(0,10)};

 const progress=(filters:Partial<OsanListFilters>={})=>{if(allCustomers.length)p.onProgress({customers:allCustomers,...filters});};
 const toggle=(key:string)=>setExpanded(v=>({...v,[key]:!v[key]}));
 const tasks=data?.tasks.filter(t=>tab==='all'||t.kind===tab)??[];
 const openTask=(t:HomeTask)=>p.onStage(t.projectId,t.targetId,t.stageSequence);
 const state=(empty:string,items?:unknown[])=>error?<p className="home-error" role="alert">{error} <button onClick={()=>setRefresh(v=>v+1)}>다시 시도</button></p>:!data?<p className="empty" role="status">불러오는 중…</p>:!items?.length?<p className="empty">{empty}</p>:null;
 const newsLabels:Record<string,string>={Complete:'Gate 완료',Edit:'사진·코멘트 수정',IssueRegistered:'공정 이상 발생',IssueRecorded:'공정 이상 기록',IssueResolved:'조치 완료',Reject:'반려',Reset:'초기화'};
 return <section className="osan-personal-home"><div className="page-title"><div><h1>내 업무 홈</h1><p>내게 온 업무와 담당 고객사의 진행 상황을 확인하세요.</p></div><span className="today">{today.replaceAll('-','.')} {new Date(`${today}T12:00:00+09:00`).toLocaleDateString('ko-KR',{weekday:'long'})}</span></div>
 <div className="dashboard"><div className="widget-column">
 <section className="widget profile"><div className="profile-top"><span className="avatar big">{p.name.slice(0,1)}</span><div><b>{p.name}님, 안녕하세요.</b><p>오산{p.department?` · ${p.department}`:''}</p></div></div><div className="profile-stats"><span>담당 고객사 <b>{data?.customers.length??'—'}</b></span><span>관리 대상 프로젝트 <b>{data?.summary.totalCount??'—'}</b></span></div><div className="customer-names">{data?.customers.length?data.customers.map(c=>c.customerName).join(' · '):data?'배정된 고객사가 없습니다.':'담당 고객사 확인 중…'}</div></section>
 <Widget name="quick" title="빠른 실행"><div className="quick-grid"><button onClick={()=>setScanning(true)}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3H3v5M16 3h5v5M3 16v5h5M21 16v5h-5M8 8h8v8H8Z"/></svg>QR 스캔</button>{p.canCreate&&<button onClick={p.onCreate}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 4v16M4 12h16"/></svg><span>프로젝트 등록</span></button>}<button onClick={()=>p.onProgress()}><NavigationIcon label="진행 현황"/>진행현황</button><button onClick={p.onNotifications}><NavigationIcon label="알림"/>내 알림</button></div></Widget>
 <Widget name="recent" title="최근 확인한 프로젝트">{recentError&&<p role="alert" className="home-error">최근 프로젝트 일부를 불러오지 못했습니다. <button onClick={()=>setRefresh(v=>v+1)}>다시 시도</button></p>}{!recent?<p className="empty">불러오는 중…</p>:!recent.length?<p className="empty">최근 확인한 프로젝트가 없습니다.</p>:recent.map(({project:v,visitedAt})=><button className="recent-row" key={v.projectId} onClick={()=>p.onProject(v.projectId)}><b>{v.title} <small>{v.productName}</small></b><span>{v.customerName} <strong>{v.workOrderNumber||'W/O 미등록'}</strong></span><small>{dateTime(visitedAt)}</small></button>)}<p className="footnote">이 기기에서 확인한 프로젝트</p></Widget>
 </div><div className="widget-column">
 <Widget name="requests" title={`내가 확인할 업무${data?` ${data.tasks.length}`:''}`} more={data&&data.tasks.length>3?()=>toggle('tasks'):undefined}><div className="tabs" role="tablist" aria-label="내 업무 구분">{([['all','전체'],['request','받은 요청'],['rejection','반려']] as const).map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} onClick={()=>setTab(key)}>{label} <b>{data?.tasks.filter(t=>key==='all'||t.kind===key).length??'—'}</b></button>)}</div>{state('확인할 업무가 없습니다.',tasks)}{!error&&(expanded.tasks?tasks:tasks.slice(0,3)).map(t=><button className="task-row" aria-label={`${t.kind==='rejection'?'반려':'진행 요청'} ${t.projectTitle} ${t.stageName}`} key={t.id} onClick={()=>openTask(t)}><span className={`badge ${t.kind==='rejection'?'red':'blue'}`}>{t.kind==='rejection'?'반려':'진행 요청'}</span><span className="row-body"><strong>{t.projectTitle} <small>{t.productName}</small></strong><span>{t.stageName}{t.comment?` · ${t.comment}`:' 진행을 요청했습니다.'}</span><small>{t.actorName} · {dateTime(t.occurredAtUtc)}</small></span><span className="chevron">›</span></button>)}{expanded.tasks&&<button className="text-button" onClick={()=>toggle('tasks')}>접기</button>}</Widget>
 <Widget name="progress" title="담당 고객사 진행 현황" more={allCustomers.length?()=>progress():undefined}><div className="metrics">{[{label:'관리 대상 프로젝트',value:data?.summary.totalCount,filter:{}},{label:'납기 초과',value:data?.summary.overdueCount,filter:{dueTo:new Date(Date.parse(`${today}T00:00:00Z`)-86400000).toISOString().slice(0,10),statuses:['NotStarted','InProgress']}},{label:'공정 이상',value:data?.summary.openIssueCount,filter:{kpi:'OpenIssue'}},{label:'HOLD',value:data?.summary.holdCount,filter:{kpi:'Hold'}}].map((m,i)=><button key={m.label} aria-label={`${m.label} ${m.value??'—'}`} disabled={!data||!allCustomers.length||!!error} onClick={()=>progress(m.filter)}><span>{m.label}</span><b className={i===1||i===2?'red':''}>{m.value??'—'}</b></button>)}</div><div className="list-label"><span>고객사별 현황</span><span>프로젝트 상태 및 공정 진행률</span></div>{state('배정된 고객사가 없습니다. 관리자에게 배정을 요청해 주세요.',data?.customers)}{!error&&data?.customers.map(c=><button className="customer-row" key={c.customerId} onClick={()=>progress({customers:[c.customerName]})}><div className="customer-heading"><b>{c.customerName}</b><span>전체 <strong>{c.totalCount}건</strong></span></div>
 <div className="customer-statuses"><span>공정 시작 전 <b>{c.notStartedCount??0}</b></span><span>공정 진행 중 <b>{c.inProgressCount}</b></span><span>포장완료 <b>{c.completedCount??0}</b></span><span>HOLD <b>{c.holdCount}</b></span></div>
 <div className="customer-progress-label"><span>전체 공정 진행률</span><strong>{c.progressPercent}%</strong></div>
 <div className="bar" role="progressbar" aria-label={`${c.customerName} 전체 공정 진행률`} aria-valuenow={c.progressPercent} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${c.progressPercent}%`}}/></div>
 <div className="customer-alerts"><span className={c.overdueCount?'red':''}>납기 초과 <b>{c.overdueCount}</b></span><span className={c.openIssueCount?'red':''}>공정 이상 <b>{c.openIssueCount}</b></span></div>
 </button>)}<p className="footnote">진행률은 프로젝트별 공정 진행률의 평균입니다. 납기가 지난 완료 건은 제외합니다. · 고객사를 누르면 프로젝트 확인</p></Widget>
 </div><div className="widget-column">
 <Widget name="deadlines" title="납기 일정" more={deadlines&&deadlines.length>3?()=>toggle('deadlines'):undefined}><div className="date-strip"><span>{Number(today.slice(5,7))}월</span>{[-2,-1,0,1,2].map(n=>{const d=new Date(Date.parse(`${today}T12:00:00Z`)+n*86400000);const date=d.toISOString().slice(0,10);return <button key={date} type="button" aria-label={`${date} 납기 일정`} aria-pressed={selectedDate===date} className={selectedDate===date?'current':''} onClick={()=>{setSelectedDate(v=>v===date?null:date);setExpanded(v=>({...v,deadlines:false}));}}>{d.getUTCDate()}<small>{['일','월','화','수','목','금','토'][d.getUTCDay()]}</small></button>})}</div>{dayLoading?<p className="empty" role="status">납기 일정을 불러오는 중…</p>:dayError?<p className="home-error" role="alert">{dayError} <button onClick={()=>setRefresh(v=>v+1)}>다시 시도</button></p>:state(selectedDate?`${selectedDate} 납기 일정이 없습니다.`:'다가오는 납기 일정이 없습니다.',deadlines)}{!error&&!dayError&&!dayLoading&&(expanded.deadlines?deadlines:deadlines?.slice(0,3))?.map(v=><button className="deadline-row" key={v.projectId} onClick={()=>p.onProject(v.projectId)}><span className={`deadline-label ${v.deliveryDate<today?'red':''}`}>{v.deliveryDate<today?'초과':v.deliveryDate===today?'오늘':'예정'}</span><span><b>{v.title}</b><small>{v.customerName} · {v.deliveryDate.slice(5).replace('-','.')}</small></span><b className={v.deliveryDate<=today?'red':''}>{formatOsanDday(v.deliveryDate,today,v.status)}</b></button>)}{expanded.deadlines&&<button className="text-button" onClick={()=>toggle('deadlines')}>접기</button>}<p className="footnote">담당 고객사 · {selectedDate??'납기 초과 및 14일 이내'} · HOLD 제외</p>{deadlineTotal!==undefined && deadlineTotal > (deadlines?.length??0) && <button className="text-button" onClick={()=>progress(deadlineFilter)}>전체 {deadlineTotal}건 보기</button>}</Widget>
 <Widget name="notices" title="공지사항" more={()=>p.onNotice()}>{noticeError?<p role="alert" className="home-error">{noticeError} <button onClick={()=>setRefresh(v=>v+1)}>다시 시도</button></p>:!notices?<p className="empty">불러오는 중…</p>:!notices.items.length?<p className="empty">등록된 공지가 없습니다.</p>:notices.items.map(v=><button className={`simple-row ${v.isRead?'':'unread'}`} key={v.noticeId} onClick={()=>p.onNotice(v.noticeId)}><span>{v.pinned&&<span className="badge red">중요</span>} {v.title}</span><small>{dateOnly(v.createdAtUtc)}</small></button>)}</Widget>
 <Widget name="news" title="최근 진행 소식" more={data&&data.news.length>3?()=>toggle('news'):undefined}>{state('최근 진행 소식이 없습니다.',data?.news)}{!error&&(expanded.news?data?.news:data?.news.slice(0,3))?.map(v=><button className="news-row" key={v.id} onClick={()=>p.onStage(v.projectId,v.targetId,v.stageSequence)}><span className={`dot ${['IssueRegistered','IssueRecorded','Reject'].includes(v.kind)?'red-dot':'green'}`}/><span><b>{v.projectTitle} · {v.stageName} {newsLabels[v.kind]??'기록 변경'}</b><small>{v.actorName} · {dateTime(v.occurredAtUtc)}</small></span></button>)}{expanded.news&&<button className="text-button" onClick={()=>toggle('news')}>접기</button>}<p className="footnote">담당 고객사의 최근 30일 소식 · 최신 20건</p></Widget>
 </div></div>{scanning&&<OsanQrScanner onClose={()=>setScanning(false)} onScan={(projectId,targetId)=>{setScanning(false);p.onScan(projectId,targetId);}}/>}</section>;
}
